#spring:
#  profiles: dev

server:
  port: 50201
  servlet:
    context-path: /api

spring:
  application:
    name: Hacker-govern-gateway

  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    timeout: 3000
    lettuce:
      pool:
        max-active: 200
        max-idle: 50
        min-idle: 24
        max-wait: 2000

zuul:
  routes:
    Hacker-api-business-web:
      path: /business/**
      serviceId: Hacker-api-business-web  # 指定服务ID(名称)，网关会从eureka中获取该服务名称下的服务实例的地址
      # url: http://www.baidu.com         # 也可指定url，此url也可以是外网地址   （例子：将请求转发到http://www.baidu.com/business）
      strip-prefix: false                 # true：代理转发时去掉前缀，false:代理转发时不去掉前缀
      sensitiveHeaders:                   # 默认zuul会屏蔽cookie，cookie不会传到下游服务，这里设置为空则取消默认的黑名单，如果设置了具体的头信息则不会传到下游服务
      # ignoredHeaders:                   # 默认为空表示不过虑任何头
    Hacker-api-business-app:
      path: /business/app/**
      serviceId: Hacker-api-business-app
      strip-prefix: false
      sensitiveHeaders:
    Hacker-api-business-alipay-shenghuohao:
      path: /business/alipay/shenghuohao/**
      serviceId: Hacker-api-business-alipay-shenghuohao
      strip-prefix: false
      sensitiveHeaders:

eureka:
  client:
    registerWithEureka: true  # 服务注册开关
    fetchRegistry: true       # 服务发现开关
    serviceUrl:               # Eureka客户端与Eureka服务端进行交互的地址，多个中间用逗号分隔
      defaultZone: ${EUREKA_SERVER:http://localhost:50101/eureka/,http://localhost:50102/eureka/}
  instance:
    prefer-ip-address:  true  # 将自己的ip地址注册到Eureka服务中
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port} # 指定实例id

ribbon:
  MaxAutoRetries: 2                # 最大重试次数，当Eureka中可以找到服务，但是服务连不上时将会重试，如果eureka中找不到服务则直接走断路器
  MaxAutoRetriesNextServer: 3      # 切换实例的重试次数
  OkToRetryOnAllOperations: false  # 对所有操作请求都进行重试，如果是get则可以，如果是post，put等操作没有实现幂等的情况下是很危险的,所以设置为false
  ConnectTimeout: 5000             # 请求连接的超时时间
  ReadTimeout: 6000                # 请求处理的超时时间